language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
env:
  - PATH=$HOME/.cargo/bin:$PATH
cache:
  pip: true
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - rustup install nightly
  - rustup default nightly

install: pip install -U tox tox-pyo3 tox-travis

script: tox
