language: python
dist: xenial
python:
- '3.5'
- '3.6'
- '3.7'
stages:
  - test
  - wheels
env:
  - PATH=$HOME/.cargo/bin:$PATH
matrix:
  include:
    - python: '3.7'
      script:
        - sudo docker build -t fastuuid_manylinux:lastest .
        - sudo docker run -v $PWD:/tmp/src fastuuid_manylinux:lastest
    stage: wheels
cache:
  pip: true
  directories:
    - $HOME/.cargo
    - $TRAVIS_BUILD_DIR/target

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - rustup install nightly
  - rustup default nightly

install: pip install -U tox pyo3-pack tox-pyo3 tox-travis

script: tox
