[package]
name = "fastuuid"
version = "0.2.0"
authors = ["Omer Katz <omer.drow@gmail.com>"]
license = "BSD3"
description = "Python bindings to Rust's UUID library."

[lib]
name = "fastuuid"
crate-type = ["cdylib"]

[dependencies.pyo3]
version = "0.7.0"
features = ["extension-module"]

[dependencies.uuid]
version = "0.7.4"
features = ["v1", "v3", "v4", "v5"]

[dependencies.byteorder]
version = "*"
